title: Blog Time
author: sofjones
email: sofjones@github.com
description: > # this means to ignore newlines until "baseurl:"
  Super cool description

# social links
twitter_username: nope # DO NOT include the @ character, or else the build will fail!
github_username:  sofjones # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
